$ErrorActionPreference = 'Stop'
$repoDir = Split-Path -Parent $PSScriptRoot
$scoopRoot = if ($env:SCOOP) { $env:SCOOP } else { Join-Path $env:USERPROFILE 'scoop' }
$utf8 = New-Object System.Text.UTF8Encoding($false)

# Export package state only. Scoop config can contain proxy credentials.
$raw = scoop export
if ($LASTEXITCODE -ne 0) { throw 'scoop export failed' }
$export = ($raw -join "`n") | ConvertFrom-Json
$buckets = @($export.buckets | Sort-Object Name | ForEach-Object {
    [ordered]@{ Name = $_.Name; Source = $_.Source }
})
$apps = @($export.apps | Sort-Object Name | ForEach-Object {
    $app = $_
    $source = $app.Source
    if ($source -eq '<auto-generated>') {
        # Preserve custom/held versions with their actual download URL and hash.
        $manifestPath = Join-Path $scoopRoot "apps\$($app.Name)\current\manifest.json"
        $manifest = Get-Content -LiteralPath $manifestPath -Raw | ConvertFrom-Json
        $manifestDir = Join-Path $repoDir 'packages\manifests'
        [void](New-Item -ItemType Directory -Path $manifestDir -Force)
        $json = $manifest | ConvertTo-Json -Depth 30
        [IO.File]::WriteAllText((Join-Path $manifestDir "$($app.Name).json"), ($json -replace "`r`n", "`n") + "`n", $utf8)
        $source = "./packages/manifests/$($app.Name).json"
    }
    [ordered]@{ Name = $app.Name; Version = $app.Version; Source = $source; Info = $app.Info }
})
$json = [ordered]@{ buckets = $buckets; apps = $apps } | ConvertTo-Json -Depth 30
[IO.File]::WriteAllText((Join-Path $repoDir 'packages\Scoopfile.json'), ($json -replace "`r`n", "`n") + "`n", $utf8)
Write-Output "Saved $($apps.Count) apps and $($buckets.Count) buckets."
